### ISSUE TITLE
Issue with phpmyadmin prefs table

### ISSUE THREAD

**Issue by mchelen** [geerlingguy/ansible-role-phpmyadmin#1]
I get this error when trying to browse a table in phpmyadmin:

```
SELECT `prefs`
FROM `phpmyadmin`.`pma_table_uiprefs`
WHERE `username` = 'root'
AND `db_name` = 'symfony'
AND `table_name` = 'users'

MySQL reports: #1146 - Table 'phpmyadmin.pma_table_uiprefs' doesn't exist
```

This might be an Ubuntu-wide issue http://stackoverflow.com/questions/20731487/phpmyadmin-pma-table-uiprefs-doesnt-exist

I was able to fix it by using the interactive setup:
`sudo dpkg-reconfigure phpmyadmin`

Tested on Ubuntu 14.04

**Comment by achton** [comment]
Same thing here. Reconfigured with dpkg and the missing `phpmyadmin` table was recreated.

**Comment by nerdstein** [comment]
Originally posted this in the wrong queue: https://github.com/geerlingguy/drupal-vm/issues/71

**Comment by nerdstein** [comment]
This still seems to be active

**Comment by geerlingguy** [comment]
Solution could be: http://stackoverflow.com/a/24937839/100134

I'll see how simple it is to just reconfigure the package as part of the setup task. Annoying... but it seems to be the status quo with Debian package installation :P

**Comment by geerlingguy** [comment]
Annoyingly, neither reconfiguring the package without user interaction (e.g. `dpkg-reconfigure -f noninteractive phpmyadmin`), nor manually running the `create_tables.sql.gz` script seems to fix this issue (see below for both solutions):

``` yaml
# Method 1 - this doesn't work.
- name: Reconfigure PHPMyAdmin (to fix an install error).
  command: dpkg-reconfigure -f noninteractive phpmyadmin
  when: install_phpmyadmin_debian.changed
  sudo: yes

# Method 2 - this doesn't work either.
- name: Expand phpMyAdmin create_tables.sql script.
  command: gzip -d /usr/share/doc/phpmyadmin/examples/create_tables.sql.gz
  when: install_phpmyadmin_debian.changed
  sudo: yes

- name: Reconfigure PHPMyAdmin (to fix an install error).
  shell: mysql < /usr/share/doc/phpmyadmin/examples/create_tables.sql
  when: install_phpmyadmin_debian.changed
  sudo: yes
```

It looks like this was caused by the Debian/Ubuntu package not being updated to take into account the [double-underscore `pma__` table names](http://sourceforge.net/p/phpmyadmin/feature-requests/628/) (originally suggested _ten years ago_) that are now defaults with phpMyAdmin installation.

I'm going to close this ticket and just recommend that Debian/Ubuntu users manually run `sudo dpkg-reconfigure phpmyadmin` after this role is finished.

Solutions to this problem:
- Run `sudo dpkg-reconfigure phpmyadmin`
- Edit `/etc/phpmyadmin/config.inc.php` and change all the table names in there manually so they're `pma__*` instead of `pma_*`
- Start using RHEL or CentOS, where this is not an issue ;)

Unfortunately, I don't want to take on the work of trying to automate these fixes; if someone else can figure out a way to automate the fix simply, please submit a PR.
