### ISSUE TITLE
PHP Apache module not being used in 7.0

### ISSUE THREAD

**Issue by jwondrusch** [geerlingguy/ansible-role-phpmyadmin#11]
When running on the geerlingguy/ubuntu1604 Vagrant box, ran into an issue where the PHP code was simply appearing in the browser instead of being interpreted.  I added the following task to my Playbook and it worked without issue:

```
  tasks:
    - name: Update php module
      apt: name=libapache2-mod-php7.0 state=installed
      notify: restart apache
```
