### ISSUE TITLE
Debian 10 package status

### ISSUE THREAD

**Issue by helmo** [geerlingguy/ansible-role-phpmyadmin#17]
The phpmyadmin package will most likely [not be included in the next Debian release](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=879741) :(

And for the same reason the most prominent ppa(nijel/phpmyadmin) has also been removed.

There is an open pull request that includes installing from source in https://github.com/geerlingguy/ansible-role-phpmyadmin/pull/13 
That PR was focused on nginx so it needs a bit of work to get it working for all debian users.

Two todo's I've identified sofar:
- missing /etc/apache2/conf-available/phpmyadmin.conf ... we can copy the debian package version
- add a version check to not re-download pma on every run.

**Comment by helmo** [comment]
New effort is visible to maintain a package for phpMyAdmin, see https://github.com/phpmyadmin/phpmyadmin/issues/15236

**Comment by geerlingguy** [comment]
It looks like they have it in `testing` and are considering moving it back to buster `stable` next.

**Comment by williamdes** [comment]
@geerlingguy Exactly
Follow progress on the GitHub issue ;)

**Comment by geerlingguy** [comment]
I bumped into this again today as I'm trying to make sure the role's tests work with Python 3... annoyingly, even if you use the `testing` packages, you have to manually install some others as well, so I'm probably going to continue holding off supporting buster in this role.

Note that you can still install from source on Buster, but as I don't even use PHPMyAdmin anymore (I've used Adminer when I need a web GUI) I don't think I'll be doing the work to add that and support it in this role.

**Comment by williamdes** [comment]
@helmo phpMyAdmin is now in Debian buster backports
See for installation: https://github.com/phpmyadmin/phpmyadmin/issues/15236#issuecomment-615954993

You can now close this issue ?

**Comment by helmo** [comment]
Yes, thanks for getting this done!

**Comment by geerlingguy** [comment]
Yay! Sitting and waiting solved the problem :D

**Comment by geerlingguy** [comment]
Note that this role seems to still need modifications to make it work on Debian 10.

**Comment by williamdes** [comment]
> Note that this role seems to still need modifications to make it work on Debian 10.

On ansible's side ?

**Comment by nukedupe** [comment]
Yes on ansible's side. `setup-Debian.yml` need a patch to ensure php-twig is from buster-backports on Debian 10 before installing phpMyAdmin. Something like:
```
- name: Ensure php-twig from buster-backports is installed.
  apt:
    name: php-twig
    state: present
    default_release: buster-backports
    update_cache: yes
  when: ansible_distribution_major_version | int == 10
```
And `:/tmp` have to be append in `/etc/phpmyadmin/apache.conf` on line `php_admin_value open_basedir`. See Issue #19 

But after that it works flawless with:
```
- name: Install phpMyAdmin
  hosts: phpmyadmin
  roles:
    - {role: geerlingguy.phpmyadmin, become: true}
  vars:
    php_packages_extra:
      - libapache2-mod-php
```
