### ISSUE TITLE
php code not executed

### ISSUE THREAD

**Issue by mmhdbw** [geerlingguy/ansible-role-phpmyadmin#20]
Hi,
I use the following playbook
```yaml
---
- name: Setup container
  hosts: mysql-server-test
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt: 
        update_cache: true
        cache_valid_time: 600
  roles:
    - role: geerlingguy.apache
    - role: geerlingguy.mysql
    - role: geerlingguy.php
    - role: geerlingguy.php-mysql
    - role: geerlingguy.phpmyadmin
 ```
to provision my fresh Ubuntu 20.04.4 instance. Provisioning shows no errors, MySQL seems to work properly, Apache as a webserver for html pages works properly.
But when I try to open path /phpadmin on my server, PHP code is just shown but not executed. Same of course for simple phpinfo-scripts.

Here are my role versions:
- geerlingguy.php, 4.8.0
- geerlingguy.phpmyadmin, 1.3.3
- geerlingguy.php-mysql, 2.1.0
- geerlingguy.apache, 3.2.0
- geerlingguy.mysql, 3.3.2

I use ansible core 2.12.3.

Although I tried various suggestions found I cannot make it work. 
Thanks a lot for any advice.

Regards, Max.
